# Introduction

Tiana Le, Sheeba Moghal, Ishaan Babbar, Liz Kovalchuk 

### Health Information National Trends and Reddit PushShift Data

Our project explores the Pushshift Reddit Dataset to examine trust in healthcare, likely narrowing specifically to r/cancer forum(s). While there are some assumptions that need to be made to pair our corroborating dataset, the Health Information National Trends Survey (HINTS) survey, with the Reddit dataset, we believe that we compare and use both of these datasets to investigate the following  questions: 

* Is public sentiment toward healthcare and cancer generally positive, or negative, in an online social platform? 
* Is there evidence of trust (or lack thereof) when the public discusses healthcare? 
* Evidence of other interpersonal conflict in healthcare discussions and emotion / sentiment analysis (e.g. sadness, disgust, surprise, joy, anger). 

# Data Sources 

## The Reddit PushShift Data Set 

The Pushshift Reddit dataset is a comprehensive collection of submissions and comments from Reddit, designed to facilitate social media research by providing easy access to historical data. Launched in 2015, Pushshift has become a crucial resource for researchers interested in analyzing user-generated content on one of the largest social media platforms.

The data leveraged from the Reddit dataset was from the provided repository of pre-processed data: 

* Spans the June-2023 to July-2024 in the 202306-202407 directory
* Spans Jan-2021 to March-2023 in the 202101-202303 directory

The data queried is of both submissions and comments from the PushShift Dataset. 

##  The Health Information National Trends Survey (HINTS)

The Health Information National Trends Survey (HINTS) is a significant research initiative launched by the National Cancer Institute (NCI) in 2001. It aims to assess how adults in the United States access and utilize health information with a particular focus on cancer-related topics. HINTS provides a rich source of data that helps researchers understand public interactions with health information, including trends in health communication, knowledge, attitudes, and behaviors regarding cancer prevention and control.

It is an excellent starting place for structured questionnaires that would be helfpul to enhance in a "more accessible" format of Reddit data. 

HINTS employs a cross-sectional, nationally representative survey methodology targeting non-institutionalized adults aged 18 years and older. This design allows for the collection of data that reflects the diverse experiences and perspectives of the U.S. population13.
Annual Administration: Initially conducted biennially, HINTS has transitioned to an annual survey format. This change enhances the ability to track evolving trends in health information access and utilization over time13.

The survey seeks information on: 
* Health information-seeking behaviors
* Cancer prevention and screening practices
* Knowledge and perceptions related to cancer risks
* Access to healthcare services
* Utilization of technology for health information37.
* Publicly Available Data: HINTS data is freely accessible through its website, allowing researchers, policymakers, and public health professionals to utilize this information for various applications, including the design and evaluation of health communication programs9.

Though HINTS was initially conducted biennially, HINTS has transitioned to an annual survey format. This change enhances the ability to track evolving trends in health information access and utilization over time. 

# Research Questions

The HINTS set of queries is extremely large. We minimized our search to the following questions to cross with Reddit PushShift data: 

### Questions from HINTS	

* SeekCancerInfo: A1. Have you ever looked for information about cancer from any source? (45) 					
* CancerFrustrated: A2b. Based on the results of your most recent search for information about cancer, how much do you agree or disagree: You felt frustrated during your search for the information: (47) 					
* CancerTrustDoctor: A3a. In general, how much would you trust information about cancer from a doctor? (50)					
* CancerTrustFamily: A3b. In general, how much would you trust information about cancer from family or friends? (51) 					
* CancerTrustGov: A3c. In general, how much would you trust information about cancer from government health agencies? (52)			
* CancerTrustCharities: A3d. In general, how much would you trust information about cancer from charitable organizations? (53) 
* CancerTrustReligiousOrgs: A3e. In general, how much would you trust information about cancer from religious organizations and leaders? (54) 
* CancerTrustScientists: A3f. In general how much would you trust information about cancer from scientists? (55) 					
* Electronic2_HealthInfo: B3a. In the past 12 months have you used the Internet to look for health or medical information? (62) 					
* MisleadingHealthInfo: B13. How much of the health information that you see on social media do you think is false or misleading? (84) 					
* TrustHCSystem: C8. How much do you trust the health care system (for example, hospitals, pharmacies, and other organizations involved in health care)? (111)

### Reddit Questions and Searches 

* Entire comments and subcomments that contain the word “cancer” 
    * (Parallel to A1, B3a, B13 in HINTS?)
    * Calculate frequency per year
* Reddits and subreddits that contain the word “cancer”
* Create subsets of data for:

* Entire comments and subcomments that contain:
    * “Frustrating” or “frustrat” and “cancer” (HINTS A2b)
    * “cancer” and “doctors” or “trust” (i.e. does not “need” to contain trust because trust is included in the NRC sentiment analysis) (HINTS A3a)
    * “cancer” and “family” or “friends” or “sister” or “brother” or “mother” or “mom” or “father” or “mother” or “cousin” or “aunt” or “uncle” or “trust” (HINTS A3b)
    * “cancer” and government_healthcare_programs = [ "medicare", "medicaid", "children’s health insurance program", "chip", "veterans health administration", "vha", "indian health service", "ihs", "federal employees health benefits program", "fehbp", "affordable care act", "aca", "health insurance marketplace", "public health depart", "local health depart", "national health service corps", "nhsc", "community health centers", "chcs", "national institutes of health", "nih", "nci", "national cancer institute" ] or “trust” (HINTS A3c)
    * “cancer” and cancer_charities = [ "american cancer society”, “acs", "cancer research institute", "breast cancer research foundation", "bcrf", "leukemia lymphoma society", "lls", "stand up to cancer", "su2c", "susan g. komen for the cure", "st. jude children’s", "national foundation for cancer research", "nfcr", "livestrong", "mesothelioma research foundation", "prostate cancer foundation", "american brain tumor association", "abta", "colon cancer coalition", "the american institute for cancer research", "aicr" ] or “trust” (HINTS A3d)
    * “cancer” and charitable_religious_organizations = [ "catholic relief services”, “crs", "world vision", "samaritan", "jewish federations of north america", "islamic relief worldwide", "buddhist global relief", "the salvation army", "christian aid", "lutheran world relief", "tzu chi foundation", "care”, “cooperative for assistance and relief everywhere", "habitat for humanity", "church world service”, “cws", "heifer international" ] or “trust” (HINTS A3e)
    * “cancer” and top_cancer_institutes = [ "researcher", "scientist", "physicians", "md anderson cancer center", "memorial sloan kettering cancer center", "msk", "mayo clinic cancer center", "johns hopkins sidney kimmel comprehensive cancer center", "cleveland clinic", "ucla medical center", "massachusetts general hospital cancer center", "duke cancer institute", "stanford cancer institute", "university of california, san francisco medical center", "ucsf", "northwestern medicine feinberg school of medicine", "university of pennsylvania abramson cancer center", "roswell park comprehensive cancer center", "fred hutchinson cancer research center" ] or “trust” (HINTS A3f)
    * “Insurance” and “cancer”
    * “Medicare” and “cancer”
    * “Medicaid” and “cancer”

# Sources: 

1. Finney Rutten, L. J., Arora, N. K., Bakken, S., & Hesse, B. W. (2022). Expanding the Health Information National Trends Survey research: A comparison of health information seeking behaviors across countries. Health Communication, 37(1), 1-10. https://doi.org/10.1080/10810730.2022.2134522
2. National Cancer Institute. (2021). Health Information National Trends Survey (HINTS). Retrieved from https://hints.cancer.gov
3. Kreps, G. L., & Neuhauser, L. (2020). The health information national trends survey: Research and implications for health communication. PubMed. https://pubmed.ncbi.nlm.nih.gov/33970822/
4. Zannettou, S., Caulfield, T., & De Cristofaro, E. (2020). The Pushshift Reddit dataset. arXiv. https://doi.org/10.48550/arXiv.2001.08435
5. Pushshift. (n.d.). Pushshift Reddit dataset. In Papers with Code. Retrieved from https://paperswithcode.com/dataset/pushshift-reddit