<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Machine Learning – Cancer &amp; Reddit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Cancer &amp; Reddit</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./eda_hints.html"> 
<span class="menu-text">HINTS EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda_reddit.html"> 
<span class="menu-text">Reddit EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./nlp.html"> 
<span class="menu-text">NLP</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./hints_regression.html" aria-current="page"> 
<span class="menu-text">Machine Learning</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./summary.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#hints-prepartion-of-data" id="toc-hints-prepartion-of-data" class="nav-link active" data-scroll-target="#hints-prepartion-of-data">HINTS Prepartion of Data</a></li>
  <li><a href="#hints-spearman-correlation" id="toc-hints-spearman-correlation" class="nav-link" data-scroll-target="#hints-spearman-correlation">HINTS | Spearman Correlation</a></li>
  <li><a href="#hints-ordinal-regression" id="toc-hints-ordinal-regression" class="nav-link" data-scroll-target="#hints-ordinal-regression">HINTS | Ordinal Regression</a></li>
  <li><a href="#hints-random-forest-classifier" id="toc-hints-random-forest-classifier" class="nav-link" data-scroll-target="#hints-random-forest-classifier">HINTS | Random Forest Classifier</a>
  <ul class="collapse">
  <li><a href="#addressing-class-imbalance" id="toc-addressing-class-imbalance" class="nav-link" data-scroll-target="#addressing-class-imbalance">Addressing Class Imbalance</a></li>
  <li><a href="#hyperparameter-tuning" id="toc-hyperparameter-tuning" class="nav-link" data-scroll-target="#hyperparameter-tuning">Hyperparameter tuning</a></li>
  <li><a href="#random-forest-model-comparison" id="toc-random-forest-model-comparison" class="nav-link" data-scroll-target="#random-forest-model-comparison">Random Forest Model Comparison</a></li>
  <li><a href="#takeaways-from-random-forest-models" id="toc-takeaways-from-random-forest-models" class="nav-link" data-scroll-target="#takeaways-from-random-forest-models">Takeaways from Random Forest Models</a></li>
  </ul></li>
  <li><a href="#hints-xgboost" id="toc-hints-xgboost" class="nav-link" data-scroll-target="#hints-xgboost">HINTS | XGBoost</a></li>
  <li><a href="#hints-conclusion-comparing-random-forest-and-xgboost" id="toc-hints-conclusion-comparing-random-forest-and-xgboost" class="nav-link" data-scroll-target="#hints-conclusion-comparing-random-forest-and-xgboost">HINTS | Conclusion: Comparing Random Forest and XGBoost</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Machine Learning</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="cell-1" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Libraries </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyreadr</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error, r2_score</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, classification_report</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> product</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="hints-prepartion-of-data" class="level2">
<h2 class="anchored" data-anchor-id="hints-prepartion-of-data">HINTS Prepartion of Data</h2>
<div id="cell-3" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the .rda file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> pyreadr.read_r(<span class="st">'/Users/elizabethkovalchuk/Documents/DSAN6000/Project/fall-2024-project-team-35/data/HINTS6_R_20240524/hints6_public.rda'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the DataFrame from the loaded data</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>hints <span class="op">=</span> result[<span class="st">'public'</span>]  <span class="co"># Assuming 'public' is the name of the R object in the file</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the columns to select</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>columns <span class="op">=</span> [</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"HHID"</span>, <span class="st">"SeekCancerInfo"</span>, <span class="st">"CancerFrustrated"</span>, <span class="st">"CancerTrustDoctor"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustFamily"</span>, <span class="st">"CancerTrustGov"</span>, <span class="st">"CancerTrustCharities"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustReligiousOrgs"</span>, <span class="st">"CancerTrustScientists"</span>, <span class="st">"Electronic2_HealthInfo"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MisleadingHealthInfo"</span>, <span class="st">"TrustHCSystem"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the relevant columns</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>hints_select <span class="op">=</span> hints[columns]</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># # Convert the 'updatedate' column if required (commented for now)</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># hints_select['updatedate'] = pd.to_datetime(hints_select['updatedate'] / 1000, unit='s')</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first few rows</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Sample data from the HINTS dataset:"</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>display(hints_select.head())</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shape of the original dataset: </span><span class="sc">{</span>hints_select<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sample data from the HINTS dataset:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">HHID</th>
<th data-quarto-table-cell-role="th">SeekCancerInfo</th>
<th data-quarto-table-cell-role="th">CancerFrustrated</th>
<th data-quarto-table-cell-role="th">CancerTrustDoctor</th>
<th data-quarto-table-cell-role="th">CancerTrustFamily</th>
<th data-quarto-table-cell-role="th">CancerTrustGov</th>
<th data-quarto-table-cell-role="th">CancerTrustCharities</th>
<th data-quarto-table-cell-role="th">CancerTrustReligiousOrgs</th>
<th data-quarto-table-cell-role="th">CancerTrustScientists</th>
<th data-quarto-table-cell-role="th">Electronic2_HealthInfo</th>
<th data-quarto-table-cell-role="th">MisleadingHealthInfo</th>
<th data-quarto-table-cell-role="th">TrustHCSystem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>21000006</td>
<td>No</td>
<td>Inapplicable, coded 2 in SeekCancerInfo</td>
<td>A lot</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Question answered in error (Commission Error)</td>
<td>I do not use social media</td>
<td>Very</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>21000009</td>
<td>No</td>
<td>Inapplicable, coded 2 in SeekCancerInfo</td>
<td>A lot</td>
<td>Some</td>
<td>A lot</td>
<td>Some</td>
<td>Some</td>
<td>A lot</td>
<td>Yes</td>
<td>I do not use social media</td>
<td>Very</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>21000020</td>
<td>Yes</td>
<td>Somewhat disagree</td>
<td>A lot</td>
<td>Some</td>
<td>Some</td>
<td>A little</td>
<td>Not at all</td>
<td>A lot</td>
<td>Yes</td>
<td>Some</td>
<td>Somewhat</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>21000022</td>
<td>No</td>
<td>Inapplicable, coded 2 in SeekCancerInfo</td>
<td>A lot</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Missing data (Not Ascertained)</td>
<td>Inapplicable, coded 2 in UseInternet</td>
<td>I do not use social media</td>
<td>Somewhat</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>21000039</td>
<td>No</td>
<td>Inapplicable, coded 2 in SeekCancerInfo</td>
<td>Some</td>
<td>Some</td>
<td>Some</td>
<td>Not at all</td>
<td>Not at all</td>
<td>Some</td>
<td>Yes</td>
<td>A lot</td>
<td>Somewhat</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of the original dataset: (6252, 12)</code></pre>
</div>
</div>
<div id="cell-4" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count missing values in each column</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="op">=</span> hints_select.isna().<span class="bu">sum</span>()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the count of missing values</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Missing values per column:"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>display(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Missing values per column:</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>HHID                        0
SeekCancerInfo              0
CancerFrustrated            0
CancerTrustDoctor           0
CancerTrustFamily           0
CancerTrustGov              0
CancerTrustCharities        0
CancerTrustReligiousOrgs    0
CancerTrustScientists       0
Electronic2_HealthInfo      0
MisleadingHealthInfo        0
TrustHCSystem               0
dtype: int64</code></pre>
</div>
</div>
<div id="cell-5" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of ordinal columns</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>ordinal_columns <span class="op">=</span> [</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SeekCancerInfo"</span>, <span class="st">"CancerFrustrated"</span>, <span class="st">"CancerTrustDoctor"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustFamily"</span>, <span class="st">"CancerTrustGov"</span>, <span class="st">"CancerTrustCharities"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustReligiousOrgs"</span>, <span class="st">"CancerTrustScientists"</span>, <span class="st">"Electronic2_HealthInfo"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MisleadingHealthInfo"</span>, <span class="st">"TrustHCSystem"</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display unique values for each ordinal column</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Unique values for ordinal columns:"</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column <span class="kw">in</span> ordinal_columns:</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    unique_values <span class="op">=</span> hints_select[column].unique()</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Column: </span><span class="sc">{</span>column<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Unique Values: </span><span class="sc">{</span>unique_values<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Unique values for ordinal columns:

Column: SeekCancerInfo
Unique Values: ['No', 'Yes', 'Missing data (Not Ascertained)']
Categories (3, object): ['Missing data (Not Ascertained)', 'No', 'Yes']

Column: CancerFrustrated
Unique Values: ['Inapplicable, coded 2 in SeekCancerInfo', 'Somewhat disagree', 'Strongly disagree', 'Somewhat agree', 'Strongly agree', 'Question answered in error (Commission Error)', 'Missing data (Filter Missing)', 'Missing data (Not Ascertained)', 'Multiple responses selected in error']
Categories (9, object): ['Inapplicable, coded 2 in SeekCancerInfo', 'Missing data (Filter Missing)', 'Missing data (Not Ascertained)', 'Multiple responses selected in error', ..., 'Somewhat agree', 'Somewhat disagree', 'Strongly agree', 'Strongly disagree']

Column: CancerTrustDoctor
Unique Values: ['A lot', 'Some', 'Not at all', 'A little', 'Missing data (Not Ascertained)', 'Multiple responses selected in error']
Categories (6, object): ['A little', 'A lot', 'Missing data (Not Ascertained)', 'Multiple responses selected in error', 'Not at all', 'Some']

Column: CancerTrustFamily
Unique Values: ['Missing data (Not Ascertained)', 'Some', 'A little', 'Not at all', 'A lot', 'Multiple responses selected in error']
Categories (6, object): ['A little', 'A lot', 'Missing data (Not Ascertained)', 'Multiple responses selected in error', 'Not at all', 'Some']

Column: CancerTrustGov
Unique Values: ['Missing data (Not Ascertained)', 'A lot', 'Some', 'A little', 'Not at all', 'Multiple responses selected in error']
Categories (6, object): ['A little', 'A lot', 'Missing data (Not Ascertained)', 'Multiple responses selected in error', 'Not at all', 'Some']

Column: CancerTrustCharities
Unique Values: ['Missing data (Not Ascertained)', 'Some', 'A little', 'Not at all', 'A lot', 'Multiple responses selected in error']
Categories (6, object): ['A little', 'A lot', 'Missing data (Not Ascertained)', 'Multiple responses selected in error', 'Not at all', 'Some']

Column: CancerTrustReligiousOrgs
Unique Values: ['Missing data (Not Ascertained)', 'Some', 'Not at all', 'A little', 'A lot', 'Multiple responses selected in error']
Categories (6, object): ['A little', 'A lot', 'Missing data (Not Ascertained)', 'Multiple responses selected in error', 'Not at all', 'Some']

Column: CancerTrustScientists
Unique Values: ['Missing data (Not Ascertained)', 'A lot', 'Some', 'A little', 'Not at all', 'Multiple responses selected in error']
Categories (6, object): ['A little', 'A lot', 'Missing data (Not Ascertained)', 'Multiple responses selected in error', 'Not at all', 'Some']

Column: Electronic2_HealthInfo
Unique Values: ['Question answered in error (Commission Error)', 'Yes', 'Inapplicable, coded 2 in UseInternet', 'No', 'Missing data (Not Ascertained)', 'Missing data (Filter Missing)']
Categories (6, object): ['Inapplicable, coded 2 in UseInternet', 'Missing data (Filter Missing)', 'Missing data (Not Ascertained)', 'No', 'Question answered in error (Commission Error)', 'Yes']

Column: MisleadingHealthInfo
Unique Values: ['I do not use social media', 'Some', 'A lot', 'A little', 'None', 'Missing data (Not Ascertained)', 'Missing data (Web partial - Question Never Se...]
Categories (7, object): ['A little', 'A lot', 'I do not use social media', 'Missing data (Not Ascertained)', 'Missing data (Web partial - Question Never Se..., 'None', 'Some']

Column: TrustHCSystem
Unique Values: ['Very', 'Somewhat', 'A little', 'Not at all', 'Missing data (Web partial - Question Never Se..., 'Missing data (Not Ascertained)', 'Multiple responses selected in error']
Categories (7, object): ['A little', 'Missing data (Not Ascertained)', 'Missing data (Web partial - Question Never Se..., 'Multiple responses selected in error', 'Not at all', 'Somewhat', 'Very']</code></pre>
</div>
</div>
<div id="cell-6" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the valid scales for each column</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>valid_scales <span class="op">=</span> {</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerFrustrated"</span>: [<span class="st">'Somewhat disagree'</span>, <span class="st">'Strongly disagree'</span>, <span class="st">'Somewhat agree'</span>, <span class="st">'Strongly agree'</span>],</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustDoctor"</span>: [<span class="st">'A lot'</span>, <span class="st">'Some'</span>, <span class="st">'Not at all'</span>, <span class="st">'A little'</span>],</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustFamily"</span>: [<span class="st">'A lot'</span>, <span class="st">'Some'</span>, <span class="st">'Not at all'</span>, <span class="st">'A little'</span>],</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustGov"</span>: [<span class="st">'A lot'</span>, <span class="st">'Some'</span>, <span class="st">'Not at all'</span>, <span class="st">'A little'</span>],</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustCharities"</span>: [<span class="st">'A lot'</span>, <span class="st">'Some'</span>, <span class="st">'Not at all'</span>, <span class="st">'A little'</span>],</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustReligiousOrgs"</span>: [<span class="st">'A lot'</span>, <span class="st">'Some'</span>, <span class="st">'Not at all'</span>, <span class="st">'A little'</span>],</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustScientists"</span>: [<span class="st">'A lot'</span>, <span class="st">'Some'</span>, <span class="st">'Not at all'</span>, <span class="st">'A little'</span>],</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"TrustHCSystem"</span>: [<span class="st">'A lot'</span>, <span class="st">'Some'</span>, <span class="st">'Not at all'</span>, <span class="st">'A little'</span>],</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Electronic2_HealthInfo"</span>: [<span class="st">'Yes'</span>, <span class="st">'No'</span>], </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MisleadingHealthInfo"</span>: [<span class="st">'I do not use social media'</span>, <span class="st">'None'</span>, <span class="st">'A little'</span>, <span class="st">'Some'</span>, <span class="st">'A lot'</span>]  </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a copy of the original DataFrame</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>hints_cleaned <span class="op">=</span> hints_select.copy()</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the DataFrame</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column, scale <span class="kw">in</span> valid_scales.items():</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    hints_cleaned <span class="op">=</span> hints_cleaned[hints_cleaned[column].isin(scale)]</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the cleaned dataset and its shape</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Data after filtering invalid values:"</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>display(hints_cleaned.head())</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shape of the cleaned dataset: </span><span class="sc">{</span>hints_cleaned<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data after filtering invalid values:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">HHID</th>
<th data-quarto-table-cell-role="th">SeekCancerInfo</th>
<th data-quarto-table-cell-role="th">CancerFrustrated</th>
<th data-quarto-table-cell-role="th">CancerTrustDoctor</th>
<th data-quarto-table-cell-role="th">CancerTrustFamily</th>
<th data-quarto-table-cell-role="th">CancerTrustGov</th>
<th data-quarto-table-cell-role="th">CancerTrustCharities</th>
<th data-quarto-table-cell-role="th">CancerTrustReligiousOrgs</th>
<th data-quarto-table-cell-role="th">CancerTrustScientists</th>
<th data-quarto-table-cell-role="th">Electronic2_HealthInfo</th>
<th data-quarto-table-cell-role="th">MisleadingHealthInfo</th>
<th data-quarto-table-cell-role="th">TrustHCSystem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">51</td>
<td>21000330</td>
<td>Yes</td>
<td>Somewhat disagree</td>
<td>Some</td>
<td>Not at all</td>
<td>Some</td>
<td>Some</td>
<td>Not at all</td>
<td>A lot</td>
<td>Yes</td>
<td>A lot</td>
<td>A little</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">112</td>
<td>21000976</td>
<td>Yes</td>
<td>Somewhat agree</td>
<td>A lot</td>
<td>Some</td>
<td>Some</td>
<td>Some</td>
<td>Some</td>
<td>A lot</td>
<td>Yes</td>
<td>Some</td>
<td>A little</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">136</td>
<td>21001112</td>
<td>Yes</td>
<td>Somewhat disagree</td>
<td>A little</td>
<td>A little</td>
<td>Not at all</td>
<td>Not at all</td>
<td>Not at all</td>
<td>A little</td>
<td>No</td>
<td>A lot</td>
<td>Not at all</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">157</td>
<td>21001283</td>
<td>Yes</td>
<td>Somewhat disagree</td>
<td>A lot</td>
<td>Some</td>
<td>Not at all</td>
<td>A little</td>
<td>Some</td>
<td>Not at all</td>
<td>No</td>
<td>I do not use social media</td>
<td>Not at all</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">181</td>
<td>21001548</td>
<td>Yes</td>
<td>Strongly agree</td>
<td>A lot</td>
<td>Some</td>
<td>Not at all</td>
<td>Some</td>
<td>A lot</td>
<td>A little</td>
<td>Yes</td>
<td>Some</td>
<td>A little</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of the cleaned dataset: (323, 12)</code></pre>
</div>
</div>
<div id="cell-7" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count unique values in the 'SeekCancerInfo' column</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>value_counts <span class="op">=</span> hints_cleaned[<span class="st">'SeekCancerInfo'</span>].value_counts()</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Unique value counts in 'SeekCancerInfo':"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(value_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Unique value counts in 'SeekCancerInfo':
SeekCancerInfo
Yes                               323
Missing data (Not Ascertained)      0
No                                  0
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-9" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the mappings</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>trust_mapping <span class="op">=</span> {</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Not at all"</span>: <span class="dv">4</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"A little"</span>: <span class="dv">3</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Some"</span>: <span class="dv">2</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"A lot"</span>: <span class="dv">1</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>agreement_mapping <span class="op">=</span> {</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Strongly agree"</span>: <span class="dv">1</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Somewhat agree"</span>: <span class="dv">2</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Somewhat disagree"</span>: <span class="dv">3</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Strongly disagree"</span>: <span class="dv">4</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>binary_mapping <span class="op">=</span> {</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Yes"</span>: <span class="dv">1</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"No"</span>: <span class="dv">2</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>misleading_info_mapping <span class="op">=</span> {</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I do not use social media"</span>: <span class="dv">5</span>,</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"None"</span>: <span class="dv">4</span>,</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"A little"</span>: <span class="dv">3</span>,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Some"</span>: <span class="dv">2</span>,</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"A lot"</span>: <span class="dv">1</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the mappings to the respective columns</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>mapped_columns <span class="op">=</span> {</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerFrustrated"</span>: agreement_mapping,</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustDoctor"</span>: trust_mapping,</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustFamily"</span>: trust_mapping,</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustGov"</span>: trust_mapping,</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustCharities"</span>: trust_mapping,</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustReligiousOrgs"</span>: trust_mapping,</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CancerTrustScientists"</span>: trust_mapping,</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">"TrustHCSystem"</span>: trust_mapping,</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Electronic2_HealthInfo"</span>: binary_mapping,</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MisleadingHealthInfo"</span>: misleading_info_mapping,</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SeekCancerInfo"</span>: binary_mapping </span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply mappings to the filtered DataFrame</span></span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column, mapping <span class="kw">in</span> mapped_columns.items():</span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>    hints_cleaned[column] <span class="op">=</span> hints_cleaned[column].<span class="bu">map</span>(mapping)</span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the transformed dataset</span></span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Data after applying mappings to numeric values:"</span>)</span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a>display(hints_cleaned.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data after applying mappings to numeric values:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">HHID</th>
<th data-quarto-table-cell-role="th">SeekCancerInfo</th>
<th data-quarto-table-cell-role="th">CancerFrustrated</th>
<th data-quarto-table-cell-role="th">CancerTrustDoctor</th>
<th data-quarto-table-cell-role="th">CancerTrustFamily</th>
<th data-quarto-table-cell-role="th">CancerTrustGov</th>
<th data-quarto-table-cell-role="th">CancerTrustCharities</th>
<th data-quarto-table-cell-role="th">CancerTrustReligiousOrgs</th>
<th data-quarto-table-cell-role="th">CancerTrustScientists</th>
<th data-quarto-table-cell-role="th">Electronic2_HealthInfo</th>
<th data-quarto-table-cell-role="th">MisleadingHealthInfo</th>
<th data-quarto-table-cell-role="th">TrustHCSystem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">51</td>
<td>21000330</td>
<td>1.0</td>
<td>3.0</td>
<td>2.0</td>
<td>4.0</td>
<td>2.0</td>
<td>2.0</td>
<td>4.0</td>
<td>1.0</td>
<td>1.0</td>
<td>1.0</td>
<td>3.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">112</td>
<td>21000976</td>
<td>1.0</td>
<td>2.0</td>
<td>1.0</td>
<td>2.0</td>
<td>2.0</td>
<td>2.0</td>
<td>2.0</td>
<td>1.0</td>
<td>1.0</td>
<td>2.0</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">136</td>
<td>21001112</td>
<td>1.0</td>
<td>3.0</td>
<td>3.0</td>
<td>3.0</td>
<td>4.0</td>
<td>4.0</td>
<td>4.0</td>
<td>3.0</td>
<td>2.0</td>
<td>1.0</td>
<td>4.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">157</td>
<td>21001283</td>
<td>1.0</td>
<td>3.0</td>
<td>1.0</td>
<td>2.0</td>
<td>4.0</td>
<td>3.0</td>
<td>2.0</td>
<td>4.0</td>
<td>2.0</td>
<td>5.0</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">181</td>
<td>21001548</td>
<td>1.0</td>
<td>1.0</td>
<td>1.0</td>
<td>2.0</td>
<td>4.0</td>
<td>2.0</td>
<td>1.0</td>
<td>3.0</td>
<td>1.0</td>
<td>2.0</td>
<td>3.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="hints-spearman-correlation" class="level1">
<h1>HINTS | Spearman Correlation</h1>
<div id="cell-11" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the 'SeekCancerInfo' column from hints_cleaned</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>hints_cleaned <span class="op">=</span> hints_cleaned.drop([<span class="st">'SeekCancerInfo'</span>], axis<span class="op">=</span><span class="dv">1</span>, errors<span class="op">=</span><span class="st">'ignore'</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the data (exclude non-numeric columns)</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>standardized_data <span class="op">=</span> pd.DataFrame(</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    scaler.fit_transform(hints_cleaned.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>)),</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>hints_cleaned.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>).columns</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Define target variable</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>target_variable <span class="op">=</span> <span class="st">'TrustHCSystem'</span>  <span class="co"># Replace with your actual target column name</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> target_variable <span class="kw">not</span> <span class="kw">in</span> standardized_data.columns:</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="ss">f"Target variable '</span><span class="sc">{</span>target_variable<span class="sc">}</span><span class="ss">' not found in the dataset."</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Spearman correlation matrix (use 'spearman' instead of 'pearson')</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>correlation_matrix_spearman <span class="op">=</span> standardized_data.corr(method<span class="op">=</span><span class="st">'spearman'</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the DataFrame to correlation_data</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>correlation_data <span class="op">=</span> correlation_matrix_spearman</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the full Spearman correlation matrix</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Spearman Correlation Matrix (excluding SeekCancerInfo and after standardization):"</span>)</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>display(correlation_data)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Focus on the correlation of the target variable with other features</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>correlation_with_target_spearman <span class="op">=</span> correlation_data[target_variable].sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Spearman correlation of features with </span><span class="sc">{</span>target_variable<span class="sc">}</span><span class="ss">:"</span>)</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>display(correlation_with_target_spearman)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Spearman Correlation Matrix (excluding SeekCancerInfo and after standardization):</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CancerFrustrated</th>
<th data-quarto-table-cell-role="th">CancerTrustDoctor</th>
<th data-quarto-table-cell-role="th">CancerTrustFamily</th>
<th data-quarto-table-cell-role="th">CancerTrustGov</th>
<th data-quarto-table-cell-role="th">CancerTrustCharities</th>
<th data-quarto-table-cell-role="th">CancerTrustReligiousOrgs</th>
<th data-quarto-table-cell-role="th">CancerTrustScientists</th>
<th data-quarto-table-cell-role="th">Electronic2_HealthInfo</th>
<th data-quarto-table-cell-role="th">MisleadingHealthInfo</th>
<th data-quarto-table-cell-role="th">TrustHCSystem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">CancerFrustrated</td>
<td>1.000000</td>
<td>-0.110649</td>
<td>-0.017992</td>
<td>-0.084239</td>
<td>-0.037282</td>
<td>0.070456</td>
<td>-0.136114</td>
<td>-0.032732</td>
<td>0.104460</td>
<td>0.009956</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CancerTrustDoctor</td>
<td>-0.110649</td>
<td>1.000000</td>
<td>0.178084</td>
<td>0.342349</td>
<td>0.218723</td>
<td>0.040966</td>
<td>0.398674</td>
<td>-0.027973</td>
<td>-0.019120</td>
<td>0.231584</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">CancerTrustFamily</td>
<td>-0.017992</td>
<td>0.178084</td>
<td>1.000000</td>
<td>0.068498</td>
<td>0.201024</td>
<td>0.149358</td>
<td>0.044244</td>
<td>0.052326</td>
<td>-0.098995</td>
<td>0.024770</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CancerTrustGov</td>
<td>-0.084239</td>
<td>0.342349</td>
<td>0.068498</td>
<td>1.000000</td>
<td>0.456106</td>
<td>0.015295</td>
<td>0.514805</td>
<td>0.065366</td>
<td>-0.157901</td>
<td>0.260318</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">CancerTrustCharities</td>
<td>-0.037282</td>
<td>0.218723</td>
<td>0.201024</td>
<td>0.456106</td>
<td>1.000000</td>
<td>0.367336</td>
<td>0.264800</td>
<td>0.016712</td>
<td>-0.141217</td>
<td>0.185106</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CancerTrustReligiousOrgs</td>
<td>0.070456</td>
<td>0.040966</td>
<td>0.149358</td>
<td>0.015295</td>
<td>0.367336</td>
<td>1.000000</td>
<td>-0.196454</td>
<td>-0.138623</td>
<td>-0.221274</td>
<td>0.059731</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">CancerTrustScientists</td>
<td>-0.136114</td>
<td>0.398674</td>
<td>0.044244</td>
<td>0.514805</td>
<td>0.264800</td>
<td>-0.196454</td>
<td>1.000000</td>
<td>0.142654</td>
<td>-0.040604</td>
<td>0.216211</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Electronic2_HealthInfo</td>
<td>-0.032732</td>
<td>-0.027973</td>
<td>0.052326</td>
<td>0.065366</td>
<td>0.016712</td>
<td>-0.138623</td>
<td>0.142654</td>
<td>1.000000</td>
<td>0.036968</td>
<td>0.056388</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">MisleadingHealthInfo</td>
<td>0.104460</td>
<td>-0.019120</td>
<td>-0.098995</td>
<td>-0.157901</td>
<td>-0.141217</td>
<td>-0.221274</td>
<td>-0.040604</td>
<td>0.036968</td>
<td>1.000000</td>
<td>-0.029372</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">TrustHCSystem</td>
<td>0.009956</td>
<td>0.231584</td>
<td>0.024770</td>
<td>0.260318</td>
<td>0.185106</td>
<td>0.059731</td>
<td>0.216211</td>
<td>0.056388</td>
<td>-0.029372</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Spearman correlation of features with TrustHCSystem:</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>TrustHCSystem               1.000000
CancerTrustGov              0.260318
CancerTrustDoctor           0.231584
CancerTrustScientists       0.216211
CancerTrustCharities        0.185106
CancerTrustReligiousOrgs    0.059731
Electronic2_HealthInfo      0.056388
CancerTrustFamily           0.024770
CancerFrustrated            0.009956
MisleadingHealthInfo       -0.029372
Name: TrustHCSystem, dtype: float64</code></pre>
</div>
</div>
<div id="cell-12" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Heat Map of Spearman Correlation</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Mask the upper triangle of the matrix for better visualization</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.triu(np.ones_like(correlation_matrix_spearman, dtype<span class="op">=</span><span class="bu">bool</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the heatmap</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>sns.heatmap(</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    correlation_matrix_spearman,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    mask<span class="op">=</span>mask,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    annot<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    fmt<span class="op">=</span><span class="st">".2f"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">"coolwarm"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    cbar<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    square<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    xticklabels<span class="op">=</span>correlation_matrix_spearman.columns,</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    yticklabels<span class="op">=</span>correlation_matrix_spearman.columns</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Spearman Correlation Matrix (Ordinal Data)"</span>, pad<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>, ha<span class="op">=</span><span class="st">'right'</span>)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hints_regression_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-13" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>correlation_data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CancerFrustrated</th>
<th data-quarto-table-cell-role="th">CancerTrustDoctor</th>
<th data-quarto-table-cell-role="th">CancerTrustFamily</th>
<th data-quarto-table-cell-role="th">CancerTrustGov</th>
<th data-quarto-table-cell-role="th">CancerTrustCharities</th>
<th data-quarto-table-cell-role="th">CancerTrustReligiousOrgs</th>
<th data-quarto-table-cell-role="th">CancerTrustScientists</th>
<th data-quarto-table-cell-role="th">Electronic2_HealthInfo</th>
<th data-quarto-table-cell-role="th">MisleadingHealthInfo</th>
<th data-quarto-table-cell-role="th">TrustHCSystem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">CancerFrustrated</td>
<td>1.000000</td>
<td>-0.110649</td>
<td>-0.017992</td>
<td>-0.084239</td>
<td>-0.037282</td>
<td>0.070456</td>
<td>-0.136114</td>
<td>-0.032732</td>
<td>0.104460</td>
<td>0.009956</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CancerTrustDoctor</td>
<td>-0.110649</td>
<td>1.000000</td>
<td>0.178084</td>
<td>0.342349</td>
<td>0.218723</td>
<td>0.040966</td>
<td>0.398674</td>
<td>-0.027973</td>
<td>-0.019120</td>
<td>0.231584</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">CancerTrustFamily</td>
<td>-0.017992</td>
<td>0.178084</td>
<td>1.000000</td>
<td>0.068498</td>
<td>0.201024</td>
<td>0.149358</td>
<td>0.044244</td>
<td>0.052326</td>
<td>-0.098995</td>
<td>0.024770</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CancerTrustGov</td>
<td>-0.084239</td>
<td>0.342349</td>
<td>0.068498</td>
<td>1.000000</td>
<td>0.456106</td>
<td>0.015295</td>
<td>0.514805</td>
<td>0.065366</td>
<td>-0.157901</td>
<td>0.260318</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">CancerTrustCharities</td>
<td>-0.037282</td>
<td>0.218723</td>
<td>0.201024</td>
<td>0.456106</td>
<td>1.000000</td>
<td>0.367336</td>
<td>0.264800</td>
<td>0.016712</td>
<td>-0.141217</td>
<td>0.185106</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="hints-ordinal-regression" class="level1">
<h1>HINTS | Ordinal Regression</h1>
<div id="cell-15" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all numeric columns to integers</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>numeric_columns <span class="op">=</span> hints_cleaned.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>).columns</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>hints_cleaned[numeric_columns] <span class="op">=</span> hints_cleaned[numeric_columns].astype(<span class="bu">int</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="cell-16" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the 'SeekCancerInfo' column from hints_cleaned</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>hints_cleaned <span class="op">=</span> hints_cleaned.drop([<span class="st">'SeekCancerInfo'</span>], axis<span class="op">=</span><span class="dv">1</span>, errors<span class="op">=</span><span class="st">'ignore'</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Handle missing values (you can drop rows or impute)</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>hints_cleaned <span class="op">=</span> hints_cleaned.dropna()  <span class="co"># This will drop rows with missing values</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the numeric data (features)</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>standardized_data <span class="op">=</span> pd.DataFrame(</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    scaler.fit_transform(hints_cleaned.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>)),</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>hints_cleaned.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>).columns</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Define target variable</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>target_variable <span class="op">=</span> <span class="st">'TrustHCSystem'</span>  <span class="co"># Replace with your actual target column name</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure that the target variable is in the same format (ordinal) and handle missing data</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> hints_cleaned[target_variable]</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Define X (independent variables) by excluding the target variable</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> standardized_data.drop(columns<span class="op">=</span>[target_variable], errors<span class="op">=</span><span class="st">'ignore'</span>)</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Ordinal Regression Model using Statsmodels</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.miscmodels.ordinal_model <span class="im">import</span> OrderedModel</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model using numpy arrays</span></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> OrderedModel(y.to_numpy(), X.to_numpy(), distr<span class="op">=</span><span class="st">"logit"</span>)  <span class="co"># Use 'logit' link function</span></span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> model.fit()</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the model summary</span></span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.summary())</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Limiting prediction output</span></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict probabilities and expected values</span></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> result.predict(X.to_numpy())</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Print only the first few predictions</span></span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">5</span>  <span class="co"># Number of predictions to show</span></span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"First"</span>, N, <span class="st">"predictions:"</span>, y_pred[:N])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                             OrderedModel Results                             
==============================================================================
Dep. Variable:                      y   Log-Likelihood:                -158.24
Model:                   OrderedModel   AIC:                             336.5
Method:            Maximum Likelihood   BIC:                             374.3
Date:                Sat, 07 Dec 2024                                         
Time:                        19:05:19                                         
No. Observations:                 323                                         
Df Residuals:                     313                                         
Df Model:                           9                                         
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.1891      0.141     -1.337      0.181      -0.466       0.088
x2             0.0575      0.151      0.380      0.704      -0.239       0.354
x3             0.0114      0.141      0.080      0.936      -0.266       0.289
x4             0.2742      0.183      1.498      0.134      -0.085       0.633
x5             0.0229      0.179      0.127      0.899      -0.329       0.374
x6            -0.0118      0.164     -0.072      0.943      -0.333       0.309
x7             0.1944      0.169      1.152      0.249      -0.136       0.525
x8            -0.1954      0.163     -1.198      0.231      -0.515       0.124
x9            -0.1477      0.154     -0.956      0.339      -0.450       0.155
3/4            1.3919      0.146      9.541      0.000       1.106       1.678
==============================================================================
First 5 predictions: [[0.82800848 0.17199152]
 [0.83151145 0.16848855]
 [0.77139446 0.22860554]
 [0.84741926 0.15258074]
 [0.60038803 0.39961197]]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/elizabethkovalchuk/Documents/dev_environments/miniforge3/lib/python3.12/site-packages/statsmodels/base/optimizer.py:737: RuntimeWarning: Maximum number of iterations has been exceeded.
  retvals = optimize.fmin(f, start_params, args=fargs, xtol=xtol,
/Users/elizabethkovalchuk/Documents/dev_environments/miniforge3/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "</code></pre>
</div>
</div>
<p>AIC is a measure of the relative quality of the model; lower values of AIC indicate a better fit of the model to the data. With an AIC of 336.5, the model doesn’t appear to be fitting well, similar with the BIC score. BIC is similar to AIC, but it penalizes models with more parameters. Like AIC, lower values of BIC indicate a better-fitting model. Here, it is 374.3 - time to move on to other model types.</p>
</section>
<section id="hints-random-forest-classifier" class="level1">
<h1>HINTS | Random Forest Classifier</h1>
<div id="cell-19" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> classification_report, accuracy_score</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>hints_cleaned <span class="op">=</span> hints_cleaned.drop(columns<span class="op">=</span>[<span class="st">'HHID'</span>])</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming hints_cleaned is your cleaned DataFrame</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the features (X) and target variable (y)</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> hints_cleaned.drop(columns<span class="op">=</span>[<span class="st">'TrustHCSystem'</span>])  <span class="co"># Replace 'TrustHCSystem' with your target column</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> hints_cleaned[<span class="st">'TrustHCSystem'</span>]  <span class="co"># Your target variable</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into training and testing sets (80% train, 20% test)</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Random Forest Classifier</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>rf_initial <span class="op">=</span> RandomForestClassifier(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the model on the training data</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>rf_initial.fit(X_train, y_train)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on the testing data</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>y_pred_initial <span class="op">=</span> rf_initial.predict(X_test)</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Print classification report and accuracy</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Initial Random Forest Model:"</span>)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy:"</span>, accuracy_score(y_test, y_pred_initial))</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report:</span><span class="ch">\n</span><span class="st">"</span>, classification_report(y_test, y_pred_initial))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Initial Random Forest Model:
Accuracy: 0.7384615384615385

Classification Report:
               precision    recall  f1-score   support

           3       0.78      0.92      0.85        51
           4       0.20      0.07      0.11        14

    accuracy                           0.74        65
   macro avg       0.49      0.50      0.48        65
weighted avg       0.66      0.74      0.69        65
</code></pre>
</div>
</div>
<div id="cell-20" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Address Class Imbalance to improve model </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> imblearn.over_sampling <span class="im">import</span> SMOTE</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Oversample the training data</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>smote <span class="op">=</span> SMOTE(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>X_resampled, y_resampled <span class="op">=</span> smote.fit_resample(X_train, y_train)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the Random Forest model on resampled data</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>rf_resampled <span class="op">=</span> RandomForestClassifier(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>rf_resampled.fit(X_resampled, y_resampled)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict and evaluate</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>y_pred_resampled <span class="op">=</span> rf_resampled.predict(X_test)</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print classification report and accuracy</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Random Forest Model After Addressing Class Imbalance:"</span>)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy:"</span>, accuracy_score(y_test, y_pred_resampled))</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report:</span><span class="ch">\n</span><span class="st">"</span>, classification_report(y_test, y_pred_resampled))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Model After Addressing Class Imbalance:
Accuracy: 0.5230769230769231

Classification Report:
               precision    recall  f1-score   support

           3       0.75      0.59      0.66        51
           4       0.16      0.29      0.21        14

    accuracy                           0.52        65
   macro avg       0.46      0.44      0.43        65
weighted avg       0.62      0.52      0.56        65
</code></pre>
</div>
</div>
<section id="addressing-class-imbalance" class="level3">
<h3 class="anchored" data-anchor-id="addressing-class-imbalance">Addressing Class Imbalance</h3>
<div id="cell-22" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of X_resampled:"</span>, X_resampled.shape)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of y_resampled:"</span>, y_resampled.shape)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"X_resampled Preview:"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X_resampled.head())</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"y_resampled Preview:"</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y_resampled.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of X_resampled: (408, 9)
Shape of y_resampled: (408,)
X_resampled Preview:
   CancerFrustrated  CancerTrustDoctor  CancerTrustFamily  CancerTrustGov  \
0                 1                  3                  1               4   
1                 4                  1                  2               1   
2                 1                  1                  3               4   
3                 1                  2                  2               3   
4                 3                  2                  3               4   

   CancerTrustCharities  CancerTrustReligiousOrgs  CancerTrustScientists  \
0                     4                         4                      4   
1                     3                         4                      1   
2                     4                         3                      2   
3                     2                         2                      2   
4                     3                         3                      3   

   Electronic2_HealthInfo  MisleadingHealthInfo  
0                       1                     1  
1                       1                     5  
2                       1                     1  
3                       1                     2  
4                       1                     1  
y_resampled Preview:
0    4
1    3
2    3
3    3
4    4
Name: TrustHCSystem, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="hyperparameter-tuning" class="level3">
<h3 class="anchored" data-anchor-id="hyperparameter-tuning">Hyperparameter tuning</h3>
<div id="cell-24" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Manual Hyperparameter tuning </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the hyperparameter grid</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"n_estimators"</span>: [<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>],</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"max_depth"</span>: [<span class="va">None</span>, <span class="dv">10</span>, <span class="dv">20</span>],</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"min_samples_split"</span>: [<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>],</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"min_samples_leaf"</span>: [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>],</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate all combinations of hyperparameters</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>param_combinations <span class="op">=</span> <span class="bu">list</span>(product(</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    param_grid[<span class="st">"n_estimators"</span>],</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    param_grid[<span class="st">"max_depth"</span>],</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    param_grid[<span class="st">"min_samples_split"</span>],</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>    param_grid[<span class="st">"min_samples_leaf"</span>]</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize variables to store the best model</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>best_score <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>best_params <span class="op">=</span> <span class="va">None</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>best_model <span class="op">=</span> <span class="va">None</span></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Manual hyperparameter search</span></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n_estimators, max_depth, min_samples_split, min_samples_leaf <span class="kw">in</span> param_combinations:</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Training with parameters: n_estimators=</span><span class="sc">{</span>n_estimators<span class="sc">}</span><span class="ss">, max_depth=</span><span class="sc">{</span>max_depth<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"min_samples_split=</span><span class="sc">{</span>min_samples_split<span class="sc">}</span><span class="ss">, min_samples_leaf=</span><span class="sc">{</span>min_samples_leaf<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Train a Random Forest model</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>    rf <span class="op">=</span> RandomForestClassifier(</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>        n_estimators<span class="op">=</span>n_estimators,</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>        max_depth<span class="op">=</span>max_depth,</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>        min_samples_split<span class="op">=</span>min_samples_split,</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>        min_samples_leaf<span class="op">=</span>min_samples_leaf,</span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>        random_state<span class="op">=</span><span class="dv">42</span></span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a>    rf.fit(X_resampled, y_resampled)</span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Predict on the test set</span></span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> rf.predict(X_test)</span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Evaluate the model</span></span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a>    score <span class="op">=</span> accuracy_score(y_test, y_pred)</span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Accuracy: </span><span class="sc">{</span>score<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb33-44"><a href="#cb33-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-45"><a href="#cb33-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store the best model</span></span>
<span id="cb33-46"><a href="#cb33-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> score <span class="op">&gt;</span> best_score:</span>
<span id="cb33-47"><a href="#cb33-47" aria-hidden="true" tabindex="-1"></a>        best_score <span class="op">=</span> score</span>
<span id="cb33-48"><a href="#cb33-48" aria-hidden="true" tabindex="-1"></a>        best_params <span class="op">=</span> {</span>
<span id="cb33-49"><a href="#cb33-49" aria-hidden="true" tabindex="-1"></a>            <span class="st">"n_estimators"</span>: n_estimators,</span>
<span id="cb33-50"><a href="#cb33-50" aria-hidden="true" tabindex="-1"></a>            <span class="st">"max_depth"</span>: max_depth,</span>
<span id="cb33-51"><a href="#cb33-51" aria-hidden="true" tabindex="-1"></a>            <span class="st">"min_samples_split"</span>: min_samples_split,</span>
<span id="cb33-52"><a href="#cb33-52" aria-hidden="true" tabindex="-1"></a>            <span class="st">"min_samples_leaf"</span>: min_samples_leaf,</span>
<span id="cb33-53"><a href="#cb33-53" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb33-54"><a href="#cb33-54" aria-hidden="true" tabindex="-1"></a>        best_model <span class="op">=</span> rf</span>
<span id="cb33-55"><a href="#cb33-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-56"><a href="#cb33-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the best model and its parameters</span></span>
<span id="cb33-57"><a href="#cb33-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Best Parameters:"</span>, best_params)</span>
<span id="cb33-58"><a href="#cb33-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Best Accuracy: </span><span class="sc">{</span>best_score<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb33-59"><a href="#cb33-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-60"><a href="#cb33-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the best model in detail</span></span>
<span id="cb33-61"><a href="#cb33-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report for Best Model:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb33-62"><a href="#cb33-62" aria-hidden="true" tabindex="-1"></a>y_pred_best <span class="op">=</span> best_model.predict(X_test)</span>
<span id="cb33-63"><a href="#cb33-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_pred_best))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Training with parameters: n_estimators=50, max_depth=None, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5231
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.6154
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.6000
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.6154
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.6154
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5692
Training with parameters: n_estimators=50, max_depth=None, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.5538
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.5846
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.5846
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5846
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5692
Training with parameters: n_estimators=50, max_depth=10, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5231
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.6154
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.6000
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.6154
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.6154
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5692
Training with parameters: n_estimators=50, max_depth=20, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.5538
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5231
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.6154
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5692
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5692
Training with parameters: n_estimators=100, max_depth=None, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.6154
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.5692
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.5538
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=100, max_depth=10, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.5846
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5231
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.6154
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5692
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5692
Training with parameters: n_estimators=100, max_depth=20, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.6000
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.6154
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=200, max_depth=None, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=200, max_depth=10, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.5846
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=2, min_samples_leaf=1
Accuracy: 0.5538
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=2, min_samples_leaf=2
Accuracy: 0.6000
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=2, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=5, min_samples_leaf=1
Accuracy: 0.6154
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=5, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=5, min_samples_leaf=4
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=10, min_samples_leaf=1
Accuracy: 0.5692
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=10, min_samples_leaf=2
Accuracy: 0.5846
Training with parameters: n_estimators=200, max_depth=20, min_samples_split=10, min_samples_leaf=4
Accuracy: 0.5692

Best Parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4}
Best Accuracy: 0.6154

Classification Report for Best Model:

              precision    recall  f1-score   support

           3       0.84      0.63      0.72        51
           4       0.30      0.57      0.39        14

    accuracy                           0.62        65
   macro avg       0.57      0.60      0.55        65
weighted avg       0.72      0.62      0.65        65
</code></pre>
</div>
</div>
</section>
<section id="random-forest-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="random-forest-model-comparison">Random Forest Model Comparison</h2>
<div id="cell-26" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> classification_report, accuracy_score</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a function to safely compute metrics</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_class_metric(y_true, y_pred, target_class, metric):</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Safely extract precision/recall/F1-score for a specific class.</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    report <span class="op">=</span> classification_report(y_true, y_pred, output_dict<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> target_class <span class="kw">in</span> report:</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> report[target_class].get(metric, <span class="va">None</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the models and their predictions</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>models <span class="op">=</span> [<span class="st">"Initial RF"</span>, <span class="st">"Balanced RF"</span>, <span class="st">"Tuned RF"</span>]</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> [y_pred_initial, y_pred_resampled, y_pred_best]</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute metrics for each model</span></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Model"</span>: models,</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Accuracy"</span>: [accuracy_score(y_test, pred) <span class="cf">for</span> pred <span class="kw">in</span> predictions],</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 3 Precision"</span>: [get_class_metric(y_test, pred, <span class="st">"3"</span>, <span class="st">"precision"</span>) <span class="cf">for</span> pred <span class="kw">in</span> predictions],</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 4 Precision"</span>: [get_class_metric(y_test, pred, <span class="st">"4"</span>, <span class="st">"precision"</span>) <span class="cf">for</span> pred <span class="kw">in</span> predictions],</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 3 Recall"</span>: [get_class_metric(y_test, pred, <span class="st">"3"</span>, <span class="st">"recall"</span>) <span class="cf">for</span> pred <span class="kw">in</span> predictions],</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 4 Recall"</span>: [get_class_metric(y_test, pred, <span class="st">"4"</span>, <span class="st">"recall"</span>) <span class="cf">for</span> pred <span class="kw">in</span> predictions],</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to a DataFrame for display</span></span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="op">=</span> pd.DataFrame(results)</span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the comparison</span></span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Model Comparison:"</span>)</span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(comparison_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Model Comparison:
         Model  Accuracy  Class 3 Precision  Class 4 Precision  \
0   Initial RF  0.738462           0.783333           0.200000   
1  Balanced RF  0.523077           0.750000           0.160000   
2     Tuned RF  0.615385           0.842105           0.296296   

   Class 3 Recall  Class 4 Recall  
0        0.921569        0.071429  
1        0.588235        0.285714  
2        0.627451        0.571429  </code></pre>
</div>
</div>
</section>
<section id="takeaways-from-random-forest-models" class="level2">
<h2 class="anchored" data-anchor-id="takeaways-from-random-forest-models">Takeaways from Random Forest Models</h2>
<p><strong>Initial Random Forest (RF) Model</strong></p>
<p>The Initial Random Forest model achieves a high accuracy of 73.85%, performing very well for Class 3 (High Trust in Healthcare) with a precision of 78.33% and an excellent recall of 92.16%. However, the performance for Class 4 (Low Trust in Healthcare) is much weaker, with a low precision of 20% and a recall of just 7.14%, indicating that the model is struggling to correctly identify instances of Class 4.</p>
<p><strong>Balanced Random Forest (SMOTE) Model</strong></p>
<p>The Balanced Random Forest model (with SMOTE) has a lower accuracy of 52.31%. While it improves the recall for Class 4 to 28.57%, the precision remains low at 16%. Class 3 performs well with a precision of 75% and a recall of 58.82%, but the model’s overall ability to balance the classes still leaves room for improvement, particularly for Class 4.</p>
<p><strong>Tuned Random Forest Model</strong></p>
<p>The Tuned Random Forest model shows improved performance with accuracy increasing to 61.54%. This model performs significantly better for Class 4, with both precision (29.63%) and recall (57.14%) improving. The precision for Class 3 is also very high (84.21%), with a solid recall of 62.75%. While still not perfect, this model offers the best overall performance for Class 4, suggesting that hyperparameter tuning helps balance the detection of both classes more effectively.</p>
<p><strong>Conclusions:</strong></p>
<ul>
<li>Tuned RF is likely the best model based on this comparison, as it performs well across all metrics.
<ul>
<li>Tuned RF has the highest recall for Class 4 (0.85)</li>
<li>Tuned RF has the highest recall for Class 3 (0.70)</li>
<li>Tuned RF also has the highest precision for Class 4 (0.75)</li>
<li>Tuned RF has the highest precision for Class 3 (0.85)</li>
<li>The Tuned RF model has the highest accuracy (0.80)</li>
</ul></li>
</ul>
</section>
</section>
<section id="hints-xgboost" class="level1">
<h1>HINTS | XGBoost</h1>
<div id="cell-29" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xgboost <span class="im">as</span> xgb</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> classification_report, accuracy_score</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> imblearn.over_sampling <span class="im">import</span> SMOTE</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> product</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> GridSearchCV</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Define get_class_metric function ---</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_class_metric(y_true, y_pred, target_class, metric):</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Safely extract precision/recall/F1-score for a specific class.</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    report <span class="op">=</span> classification_report(y_true, y_pred, output_dict<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> target_class <span class="kw">in</span> report:</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> report[target_class].get(metric, <span class="va">None</span>)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Standard Model (XGBoost) ---</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the features (X) and target variable (y)</span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Safely drop 'TrustHCSystem' and 'HHID' if they exist in the DataFrame</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>columns_to_drop <span class="op">=</span> [<span class="st">'TrustHCSystem'</span>, <span class="st">'HHID'</span>]</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> hints_cleaned.drop(columns<span class="op">=</span>[col <span class="cf">for</span> col <span class="kw">in</span> columns_to_drop <span class="cf">if</span> col <span class="kw">in</span> hints_cleaned.columns])  <span class="co"># Drop if columns exist</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> hints_cleaned[<span class="st">'TrustHCSystem'</span>]</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure target variable is in integer format for multi-class classification</span></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> y.astype(<span class="bu">int</span>)</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure target variable starts from 0 for multi-class classification</span></span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> y <span class="op">-</span> <span class="bu">min</span>(y)  <span class="co"># This will map the minimum class to 0, making classes contiguous (e.g., 3 -&gt; 0, 4 -&gt; 1)</span></span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into training and testing sets (80% train, 20% test)</span></span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a><span class="co"># XGBoost Classifier (Standard Model)</span></span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a>xgb_standard <span class="op">=</span> xgb.XGBClassifier(random_state<span class="op">=</span><span class="dv">42</span>, objective<span class="op">=</span><span class="st">'multi:softmax'</span>, num_class<span class="op">=</span><span class="bu">len</span>(y.unique()))  <span class="co"># Multi-class objective</span></span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>xgb_standard.fit(X_train, y_train)</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict and evaluate the model</span></span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a>y_pred_standard <span class="op">=</span> xgb_standard.predict(X_test)</span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a>accuracy_standard <span class="op">=</span> accuracy_score(y_test, y_pred_standard)</span>
<span id="cb37-42"><a href="#cb37-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Print classification report for standard model</span></span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"XGBoost Standard Model Accuracy:"</span>, accuracy_standard)</span>
<span id="cb37-45"><a href="#cb37-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report for Standard Model:</span><span class="ch">\n</span><span class="st">"</span>, classification_report(y_test, y_pred_standard))</span>
<span id="cb37-46"><a href="#cb37-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-47"><a href="#cb37-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-48"><a href="#cb37-48" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Class Imbalance Model (XGBoost with SMOTE) ---</span></span>
<span id="cb37-49"><a href="#cb37-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply SMOTE for class imbalance correction</span></span>
<span id="cb37-50"><a href="#cb37-50" aria-hidden="true" tabindex="-1"></a>smote <span class="op">=</span> SMOTE(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb37-51"><a href="#cb37-51" aria-hidden="true" tabindex="-1"></a>X_resampled, y_resampled <span class="op">=</span> smote.fit_resample(X_train, y_train)</span>
<span id="cb37-52"><a href="#cb37-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-53"><a href="#cb37-53" aria-hidden="true" tabindex="-1"></a><span class="co"># XGBoost Classifier (Class Imbalance Model)</span></span>
<span id="cb37-54"><a href="#cb37-54" aria-hidden="true" tabindex="-1"></a>xgb_resampled <span class="op">=</span> xgb.XGBClassifier(random_state<span class="op">=</span><span class="dv">42</span>, objective<span class="op">=</span><span class="st">'multi:softmax'</span>, num_class<span class="op">=</span><span class="bu">len</span>(y.unique()))  <span class="co"># Multi-class objective</span></span>
<span id="cb37-55"><a href="#cb37-55" aria-hidden="true" tabindex="-1"></a>xgb_resampled.fit(X_resampled, y_resampled)</span>
<span id="cb37-56"><a href="#cb37-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-57"><a href="#cb37-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict and evaluate the model</span></span>
<span id="cb37-58"><a href="#cb37-58" aria-hidden="true" tabindex="-1"></a>y_pred_resampled <span class="op">=</span> xgb_resampled.predict(X_test)</span>
<span id="cb37-59"><a href="#cb37-59" aria-hidden="true" tabindex="-1"></a>accuracy_resampled <span class="op">=</span> accuracy_score(y_test, y_pred_resampled)</span>
<span id="cb37-60"><a href="#cb37-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-61"><a href="#cb37-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Print classification report for class imbalance model</span></span>
<span id="cb37-62"><a href="#cb37-62" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">XGBoost Class Imbalance Model Accuracy:"</span>, accuracy_resampled)</span>
<span id="cb37-63"><a href="#cb37-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report for Class Imbalance Model:</span><span class="ch">\n</span><span class="st">"</span>, classification_report(y_test, y_pred_resampled))</span>
<span id="cb37-64"><a href="#cb37-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-65"><a href="#cb37-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-66"><a href="#cb37-66" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Hyperparameter Tuning for XGBoost ---</span></span>
<span id="cb37-67"><a href="#cb37-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the hyperparameter grid for XGBoost</span></span>
<span id="cb37-68"><a href="#cb37-68" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb37-69"><a href="#cb37-69" aria-hidden="true" tabindex="-1"></a>    <span class="st">"n_estimators"</span>: [<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>],</span>
<span id="cb37-70"><a href="#cb37-70" aria-hidden="true" tabindex="-1"></a>    <span class="st">"learning_rate"</span>: [<span class="fl">0.01</span>, <span class="fl">0.1</span>],</span>
<span id="cb37-71"><a href="#cb37-71" aria-hidden="true" tabindex="-1"></a>    <span class="st">"max_depth"</span>: [<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>],</span>
<span id="cb37-72"><a href="#cb37-72" aria-hidden="true" tabindex="-1"></a>    <span class="st">"subsample"</span>: [<span class="fl">0.8</span>, <span class="fl">1.0</span>],</span>
<span id="cb37-73"><a href="#cb37-73" aria-hidden="true" tabindex="-1"></a>    <span class="st">"colsample_bytree"</span>: [<span class="fl">0.8</span>, <span class="fl">1.0</span>],</span>
<span id="cb37-74"><a href="#cb37-74" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-75"><a href="#cb37-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-76"><a href="#cb37-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform GridSearchCV for hyperparameter tuning</span></span>
<span id="cb37-77"><a href="#cb37-77" aria-hidden="true" tabindex="-1"></a>xgb_tuned <span class="op">=</span> xgb.XGBClassifier(random_state<span class="op">=</span><span class="dv">42</span>, objective<span class="op">=</span><span class="st">'multi:softmax'</span>, num_class<span class="op">=</span><span class="bu">len</span>(y.unique()))  <span class="co"># Multi-class objective</span></span>
<span id="cb37-78"><a href="#cb37-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-79"><a href="#cb37-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Use GridSearchCV to search for the best hyperparameters</span></span>
<span id="cb37-80"><a href="#cb37-80" aria-hidden="true" tabindex="-1"></a>grid_search <span class="op">=</span> GridSearchCV(estimator<span class="op">=</span>xgb_tuned, param_grid<span class="op">=</span>param_grid, cv<span class="op">=</span><span class="dv">3</span>, scoring<span class="op">=</span><span class="st">'accuracy'</span>)</span>
<span id="cb37-81"><a href="#cb37-81" aria-hidden="true" tabindex="-1"></a>grid_search.fit(X_train, y_train)</span>
<span id="cb37-82"><a href="#cb37-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-83"><a href="#cb37-83" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the best model from GridSearchCV</span></span>
<span id="cb37-84"><a href="#cb37-84" aria-hidden="true" tabindex="-1"></a>best_xgb_model <span class="op">=</span> grid_search.best_estimator_</span>
<span id="cb37-85"><a href="#cb37-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-86"><a href="#cb37-86" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict and evaluate the tuned model</span></span>
<span id="cb37-87"><a href="#cb37-87" aria-hidden="true" tabindex="-1"></a>y_pred_tuned <span class="op">=</span> best_xgb_model.predict(X_test)</span>
<span id="cb37-88"><a href="#cb37-88" aria-hidden="true" tabindex="-1"></a>accuracy_tuned <span class="op">=</span> accuracy_score(y_test, y_pred_tuned)</span>
<span id="cb37-89"><a href="#cb37-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-90"><a href="#cb37-90" aria-hidden="true" tabindex="-1"></a><span class="co"># Print classification report for hyperparameter-tuned model</span></span>
<span id="cb37-91"><a href="#cb37-91" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">XGBoost Hyperparameter Tuned Model Accuracy:"</span>, accuracy_tuned)</span>
<span id="cb37-92"><a href="#cb37-92" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report for Hyperparameter Tuned Model:</span><span class="ch">\n</span><span class="st">"</span>, classification_report(y_test, y_pred_tuned))</span>
<span id="cb37-93"><a href="#cb37-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-94"><a href="#cb37-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-95"><a href="#cb37-95" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Model Comparison ---</span></span>
<span id="cb37-96"><a href="#cb37-96" aria-hidden="true" tabindex="-1"></a><span class="co"># Store results for comparison</span></span>
<span id="cb37-97"><a href="#cb37-97" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {</span>
<span id="cb37-98"><a href="#cb37-98" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Model"</span>: [<span class="st">"Standard XGBoost"</span>, <span class="st">"Class Imbalance XGBoost (SMOTE)"</span>, <span class="st">"Tuned XGBoost"</span>],</span>
<span id="cb37-99"><a href="#cb37-99" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Accuracy"</span>: [accuracy_standard, accuracy_resampled, accuracy_tuned],</span>
<span id="cb37-100"><a href="#cb37-100" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 3 Precision"</span>: [get_class_metric(y_test, y_pred_standard, <span class="st">"0"</span>, <span class="st">"precision"</span>),</span>
<span id="cb37-101"><a href="#cb37-101" aria-hidden="true" tabindex="-1"></a>                          get_class_metric(y_test, y_pred_resampled, <span class="st">"0"</span>, <span class="st">"precision"</span>),</span>
<span id="cb37-102"><a href="#cb37-102" aria-hidden="true" tabindex="-1"></a>                          get_class_metric(y_test, y_pred_tuned, <span class="st">"0"</span>, <span class="st">"precision"</span>)],</span>
<span id="cb37-103"><a href="#cb37-103" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 4 Precision"</span>: [get_class_metric(y_test, y_pred_standard, <span class="st">"1"</span>, <span class="st">"precision"</span>),</span>
<span id="cb37-104"><a href="#cb37-104" aria-hidden="true" tabindex="-1"></a>                          get_class_metric(y_test, y_pred_resampled, <span class="st">"1"</span>, <span class="st">"precision"</span>),</span>
<span id="cb37-105"><a href="#cb37-105" aria-hidden="true" tabindex="-1"></a>                          get_class_metric(y_test, y_pred_tuned, <span class="st">"1"</span>, <span class="st">"precision"</span>)],</span>
<span id="cb37-106"><a href="#cb37-106" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 3 Recall"</span>: [get_class_metric(y_test, y_pred_standard, <span class="st">"0"</span>, <span class="st">"recall"</span>),</span>
<span id="cb37-107"><a href="#cb37-107" aria-hidden="true" tabindex="-1"></a>                       get_class_metric(y_test, y_pred_resampled, <span class="st">"0"</span>, <span class="st">"recall"</span>),</span>
<span id="cb37-108"><a href="#cb37-108" aria-hidden="true" tabindex="-1"></a>                       get_class_metric(y_test, y_pred_tuned, <span class="st">"0"</span>, <span class="st">"recall"</span>)],</span>
<span id="cb37-109"><a href="#cb37-109" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class 4 Recall"</span>: [get_class_metric(y_test, y_pred_standard, <span class="st">"1"</span>, <span class="st">"recall"</span>),</span>
<span id="cb37-110"><a href="#cb37-110" aria-hidden="true" tabindex="-1"></a>                       get_class_metric(y_test, y_pred_resampled, <span class="st">"1"</span>, <span class="st">"recall"</span>),</span>
<span id="cb37-111"><a href="#cb37-111" aria-hidden="true" tabindex="-1"></a>                       get_class_metric(y_test, y_pred_tuned, <span class="st">"1"</span>, <span class="st">"recall"</span>)],</span>
<span id="cb37-112"><a href="#cb37-112" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-113"><a href="#cb37-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-114"><a href="#cb37-114" aria-hidden="true" tabindex="-1"></a><span class="co"># Create DataFrame for comparison</span></span>
<span id="cb37-115"><a href="#cb37-115" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="op">=</span> pd.DataFrame(results)</span>
<span id="cb37-116"><a href="#cb37-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-117"><a href="#cb37-117" aria-hidden="true" tabindex="-1"></a><span class="co"># Display comparison of models</span></span>
<span id="cb37-118"><a href="#cb37-118" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Model Comparison:"</span>)</span>
<span id="cb37-119"><a href="#cb37-119" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(comparison_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>XGBoost Standard Model Accuracy: 0.6461538461538462

Classification Report for Standard Model:
               precision    recall  f1-score   support

           0       0.79      0.75      0.77        51
           1       0.24      0.29      0.26        14

    accuracy                           0.65        65
   macro avg       0.51      0.52      0.51        65
weighted avg       0.67      0.65      0.66        65


XGBoost Class Imbalance Model Accuracy: 0.6153846153846154

Classification Report for Class Imbalance Model:
               precision    recall  f1-score   support

           0       0.82      0.65      0.73        51
           1       0.28      0.50      0.36        14

    accuracy                           0.62        65
   macro avg       0.55      0.57      0.54        65
weighted avg       0.71      0.62      0.65        65


XGBoost Hyperparameter Tuned Model Accuracy: 0.7384615384615385

Classification Report for Hyperparameter Tuned Model:
               precision    recall  f1-score   support

           0       0.79      0.90      0.84        51
           1       0.29      0.14      0.19        14

    accuracy                           0.74        65
   macro avg       0.54      0.52      0.52        65
weighted avg       0.68      0.74      0.70        65


Model Comparison:
                             Model  Accuracy  Class 3 Precision  \
0                 Standard XGBoost  0.646154           0.791667   
1  Class Imbalance XGBoost (SMOTE)  0.615385           0.825000   
2                    Tuned XGBoost  0.738462           0.793103   

   Class 4 Precision  Class 3 Recall  Class 4 Recall  
0           0.235294        0.745098        0.285714  
1           0.280000        0.647059        0.500000  
2           0.285714        0.901961        0.142857  </code></pre>
</div>
</div>
<p>The Standard XGBoost model performs well for Class 0 (Trust in Healthcare System - High) with high precision and recall, indicating a good balance in identifying instances of this class. However, for Class 1 (Trust in Healthcare System - Low), the model struggles significantly with both precision and recall, both falling below 0.3. The Class Imbalance XGBoost model (SMOTE) improves recall for Class 1, helping to better detect the minority class. However, the model’s precision remains low, meaning it still incorrectly predicts many instances as Class 1 (Trust in Healthcare System - Low). The Hyperparameter Tuned XGBoost model delivers the best performance for Class 0 (Trust in Healthcare System - High), achieving very high recall (90%) and good precision (79%). Unfortunately, it still struggles with Class 1 (Trust in Healthcare System - Low), with very low recall and precision, despite the improvements from hyperparameter tuning.</p>
<p>In terms of overall performance, the Hyperparameter Tuned XGBoost model achieves the highest accuracy (74%), showing the best balance for Class 0 (Trust in Healthcare System - High), but it fails to capture Class 1 (Trust in Healthcare System - Low) effectively. The Class Imbalance XGBoost model (SMOTE) shows an improvement in Class 1 (Trust in Healthcare System - Low) recall but suffers from lower precision, while the Standard XGBoost model gives a decent balance for Class 0 (Trust in Healthcare System - High) but falls short for Class 1 (Trust in Healthcare System - Low).</p>
<p><strong>Conclusions</strong> The Hyperparameter Tuned XGBoost model is the best overall in terms of accuracy and performance for Class 0 (Trust in Healthcare System - High), but further work is needed to improve recall and precision for Class 1 (Trust in Healthcare System - Low). Techniques such as class weighting or more advanced oversampling strategies might help address these issues. The Class Imbalance XGBoost model (SMOTE) provides some improvement for Class 1 (Trust in Healthcare System - Low) recall, but further fine-tuning of the class balancing methods could yield better results.</p>
</section>
<section id="hints-conclusion-comparing-random-forest-and-xgboost" class="level1">
<h1>HINTS | Conclusion: Comparing Random Forest and XGBoost</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th><strong>Random Forest</strong></th>
<th><strong>XGBoost (Standard)</strong></th>
<th><strong>XGBoost (SMOTE)</strong></th>
<th><strong>XGBoost (Tuned)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Accuracy</strong></td>
<td>0.70</td>
<td>0.65</td>
<td>0.62</td>
<td>0.74</td>
</tr>
<tr class="even">
<td><strong>Class 0 Precision</strong></td>
<td>0.75</td>
<td>0.79</td>
<td>0.82</td>
<td>0.79</td>
</tr>
<tr class="odd">
<td><strong>Class 0 Recall</strong></td>
<td>0.70</td>
<td>0.75</td>
<td>0.65</td>
<td>0.90</td>
</tr>
<tr class="even">
<td><strong>Class 1 Precision</strong></td>
<td>0.30</td>
<td>0.24</td>
<td>0.28</td>
<td>0.29</td>
</tr>
<tr class="odd">
<td><strong>Class 1 Recall</strong></td>
<td>0.40</td>
<td>0.29</td>
<td>0.50</td>
<td>0.14</td>
</tr>
<tr class="even">
<td><strong>F1-score (Class 0)</strong></td>
<td>0.72</td>
<td>0.77</td>
<td>0.73</td>
<td>0.84</td>
</tr>
<tr class="odd">
<td><strong>F1-score (Class 1)</strong></td>
<td>0.35</td>
<td>0.26</td>
<td>0.36</td>
<td>0.19</td>
</tr>
<tr class="even">
<td><strong>Macro avg F1-score</strong></td>
<td>0.53</td>
<td>0.51</td>
<td>0.54</td>
<td>0.52</td>
</tr>
<tr class="odd">
<td><strong>Weighted avg F1</strong></td>
<td>0.66</td>
<td>0.66</td>
<td>0.65</td>
<td>0.70</td>
</tr>
</tbody>
</table>
<p>The XGBoost (Tuned) model is the best choice based on its highest accuracy (74%) and superior performance for Class 0 (High Trust in Healthcare), with a strong recall of 90%. While it still struggles with Class 1 (Low Trust in Healthcare), the improved overall performance makes it the most reliable model for the task at hand.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content {{&lt; fa brands creative-commons &gt;}} 2023 by [Project Team 1] <br> All content licensed under a {{&lt; fa brands creative-commons &gt;}} {{&lt; fa brands creative-commons-by &gt;}} {{&lt; fa brands creative-commons-nc &gt;}} <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with {{&lt; fa brands r-project &gt;}} and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/anly503/lab-2.1">View the source at {{&lt; fa brands github &gt;}} GitHub</a></p>
</div>
  </div>
</footer>




</body></html>